
export type Language = 'en' | 'hi' | 'mr' | 'fr';

export const translations = {
  en: {
    nav: { home: 'Home', recipes: 'Recipes', gallery: 'Gallery', planner: 'Planner', connect: 'Connect', talk: 'Talk Veg' },
    hero: { tradition: 'Pratishtha • Tradition', title: 'Veg Eat', subtitle: 'by Umesh Bade', description: "Discover the aromatic secrets of Bharat's regional kitchens. A warming journey through spices, soul, and heritage.", explore: 'Explore Recipes', talkChef: 'Talk to Chef', foodies: 'Foodies Explored Today' },
    recipes: { heritage: 'Dharohar • Heritage', title: 'Regional Jewels', description: 'Each region of India brings a unique tempering, a secret spice, and a warming soul to the vegetarian table.', allRegions: 'All Regions', spiceLevel: 'Spice Level', time: 'Time', energy: 'Energy', discoverAll: 'Discover All Regional Treasures' },
    gallery: { subtitle: 'Taste with your eyes', title: 'The Visual Kitchen', description: 'A celebration of colors, textures, and the vibrant life of Indian vegetarian cuisine.', curated: 'Curated by Umesh Bade', viewDetails: 'View Details' },
    planner: { title: 'Seasonal Planner', description: 'Align your diet with the rhythms of nature and the wisdom of Ayurveda.', presentMoment: 'The Present Moment', weeklyRituals: 'Weekly Culinary Rituals', wisdomTitle: 'Honoring your Agni', wisdomDesc: 'Your digestive fire is strongest when the sun is at its peak. Ensure your heaviest meal is between 12:00 PM and 1:30 PM.', ritualButton: 'Get Ritual Reminders' },
    connect: { sampark: 'Sampark • Contact', title: 'Connect With Us', description: "Whether you're looking for a specific recipe, want to share feedback, or explore partnerships, our kitchen doors are always open.", direct: 'Direct Channels', emailUs: 'Email Us', studio: 'Studio', location: 'Pune, Maharashtra, Bharat', quote: 'Cooking is a conversation between the soul and the soil.', fullName: 'Full Name', email: 'Email Address', phone: 'Contact Number', reason: 'Reason for Connecting', message: 'Your Message', send: 'Send Message', selectReason: 'Select a reason', successTitle: 'Dhanyawad!', successDesc: 'Thank you for reaching out. Umesh will connect with you shortly.' },
    footer: { quote: 'Elevating the plant-based lifestyle with passion and tradition.', visits: 'Total Profile Visits', curated: 'Curated & Crafted by', rights: 'ALL RIGHTS RESERVED' }
  },
  hi: {
    nav: { home: 'मुख्य', recipes: 'रेसिपी', gallery: 'गैलरी', planner: 'योजना', connect: 'संपर्क', talk: 'बात करें' },
    hero: { tradition: 'प्रतिष्ठा • परंपरा', title: 'वेज ईट', subtitle: 'उमेश बाडे द्वारा', description: "भारत की क्षेत्रीय रसोई के सुगंधित रहस्यों को जानें। मसालों, आत्मा और विरासत के माध्यम से एक सुखद यात्रा।", explore: 'रेसिपी देखें', talkChef: 'शेफ से बात करें', foodies: 'आज कितने लोगों ने देखा' },
    recipes: { heritage: 'धरोहर • विरासत', title: 'क्षेत्रीय रत्न', description: 'भारत का प्रत्येक क्षेत्र शाकाहारी भोजन में एक अनोखा तड़का, एक गुप्त मसाला और एक गर्म आत्मा लाता है।', allRegions: 'सभी क्षेत्र', spiceLevel: 'मसाला स्तर', time: 'समय', energy: 'ऊर्जा', discoverAll: 'सभी क्षेत्रीय खजाने खोजें' },
    gallery: { subtitle: 'आंखों से स्वाद लें', title: 'दृश्य रसोई', description: 'भारतीय शाकाहारी व्यंजनों के रंगों, बनावट और जीवंत जीवन का उत्सव।', curated: 'उमेश बाडे द्वारा क्यूरेटेड', viewDetails: 'विवरण देखें' },
    planner: { title: 'मौसमी योजनाकार', description: 'अपने आहार को प्रकृति की लय और आयुर्वेद के ज्ञान के साथ जोड़ें।', presentMoment: 'वर्तमान क्षण', weeklyRituals: 'साप्ताहिक पाक अनुष्ठान', wisdomTitle: 'अपनी अग्नि का सम्मान करें', wisdomDesc: 'जब सूरज अपने चरम पर होता है तो आपकी पाचन शक्ति सबसे मजबूत होती है। 12:00 से 1:30 के बीच भोजन करें।', ritualButton: 'अनुष्ठान अनुस्मारक प्राप्त करें' },
    connect: { sampark: 'संपर्क करें', title: 'हमसे जुड़ें', description: "चाहे आप कोई विशेष रेसिपी ढूंढ रहे हों, फीडबैक देना चाहते हों, हमारा रसोईघर हमेशा खुला है।", direct: 'सीधे चैनल', emailUs: 'हमें ईमेल करें', studio: 'स्टूडियो', location: 'पुणे, महाराष्ट्र, भारत', quote: 'खाना पकाना आत्मा और मिट्टी के बीच की बातचीत है।', fullName: 'पूरा नाम', email: 'ईमेल पता', phone: 'संपर्क नंबर', reason: 'संपर्क का कारण', message: 'आपका संदेश', send: 'संदेश भेजें', selectReason: 'एक कारण चुनें', successTitle: 'धन्यवाद!', successDesc: 'संपर्क करने के लिए धन्यवाद। उमेश आपसे जल्द ही जुड़ेंगे।' },
    footer: { quote: 'जुनून और परंपरा के साथ शाकाहारी जीवन शैली को ऊपर उठाना।', visits: 'कुल प्रोफ़ाइल विज़िट', curated: 'क्यूरेटेड और क्राफ्टेड', rights: 'सर्वाधिकार सुरक्षित' }
  },
  mr: {
    nav: { home: 'मुख्य', recipes: 'रेसिपी', gallery: 'गॅलरी', planner: 'नियोजन', connect: 'संपर्क', talk: 'बोला' },
    hero: { tradition: 'प्रतिष्ठा • परंपरा', title: 'व्हेज ईट', subtitle: 'उमेश बाडे तर्फे', description: "भारतातील प्रादेशिक स्वयंपाकघरातील सुगंधी रहस्ये शोधा. मसाले, आत्मा आणि वारसा याद्वारे एक सुखद प्रवास।", explore: 'रेसिपी शोधा', talkChef: 'शेफशी बोला', foodies: 'आज भेट दिलेले खवय्ये' },
    recipes: { heritage: 'धरोहर • वारसा', title: 'प्रादेशिक रत्ने', description: 'भारतातील प्रत्येक प्रदेश शाकाहारी जेवणात एक वेगळा तडका, गुप्त मसाला आणि एक उबदार आत्मा आणतो।', allRegions: 'सर्व प्रदेश', spiceLevel: 'तिखटपणा', time: 'वेळ', energy: 'ऊर्जा', discoverAll: 'सर्व प्रादेशिक खजिना शोधा' },
    gallery: { subtitle: 'डोळ्यांनी चव घ्या', title: 'दृश्य स्वयंपाकघर', description: 'भारतीय शाकाहारी पाककृतींचे रंग, पोत आणि दोलायमान जीवनाचा उत्सव।', curated: 'उमेश बाडे यांनी क्युरेट केलेले', viewDetails: 'तपशील पहा' },
    planner: { title: 'हंगामी नियोजन', description: 'निसर्गाच्या लयानुसार आणि आयुर्वेदाच्या ज्ञानानुसार आपला आहार संतुलित करा।', presentMoment: 'सध्याची वेळ', weeklyRituals: 'साप्ताहिक पाक विधी', wisdomTitle: 'तुमच्या अग्नीचा आदर करा', wisdomDesc: 'सूर्य जेव्हा शिखरावर असतो तेव्हा तुमची पचनशक्ती सर्वात मजबूत असते। दुपारी १२:०० ते १:३० दरम्यान जेवा।', ritualButton: 'स्मरणपत्रे मिळवा' },
    connect: { sampark: 'संपर्क साधा', title: 'आमच्याशी जोडा', description: "तुम्ही एखादी रेसिपी शोधत असाल किंवा भागीदारी करू इच्छित असाल, आमचे दरवाजे नेहमी उघडे आहेत।", direct: 'थेट चॅनेल', emailUs: 'ईमेल करा', studio: 'स्टुडिओ', location: 'पुणे, महाराष्ट्र, भारत', quote: 'स्वयंपाक करणे म्हणजे आत्मा आणि माती यांच्यातील संवाद आहे।', fullName: 'पूर्ण नाव', email: 'ईमेल पत्ता', phone: 'संपर्क क्रमांक', reason: 'संपर्काचे कारण', message: 'तुमचा संदेश', send: 'संदेश पाठवा', selectReason: 'कारण निवडा', successTitle: 'धन्यवाद!', successDesc: 'संपर्क केल्याबद्दल धन्यवाद. उमेश लवकरच तुमच्याशी संपर्क साधतील।' },
    footer: { quote: 'शाकाहारी जीवनशैली उत्कटतेने आणि परंपरेने समृद्ध करणे।', visits: 'एकूण प्रोफ़ाइल भेटी', curated: 'उमेश बाडे द्वारे क्युरेट केलेले', rights: 'सर्व हक्क राखीव' }
  },
  fr: {
    nav: { home: 'Accueil', recipes: 'Recettes', gallery: 'Galerie', planner: 'Planning', connect: 'Contact', talk: 'Parler Veg' },
    hero: { tradition: 'Pratishtha • Tradition', title: 'Veg Eat', subtitle: 'par Umesh Bade', description: "Découvrez les secrets aromatiques des cuisines régionales de l'Inde. Un voyage chaleureux à travers les épices et l'héritage.", explore: 'Explorer les Recettes', talkChef: 'Parler au Chef', foodies: 'Visiteurs Aujourd’hui' },
    recipes: { heritage: 'Dharohar • Héritage', title: 'Joyaux Régionaux', description: "Chaque région de l'Inde apporte un tempérament unique et une épice secrète à la table végétarienne.", allRegions: 'Toutes Régions', spiceLevel: "Niveau d'Épices", time: 'Temps', energy: 'Énergie', discoverAll: 'Découvrir tous les Trésors' },
    gallery: { subtitle: 'Goûtez avec vos yeux', title: 'La Cuisine Visuelle', description: 'Une célébration des couleurs, des textures et de la vie vibrante de la cuisine indienne végétarienne.', curated: 'Édité par Umesh Bade', viewDetails: 'Voir Détails' },
    planner: { title: 'Planificateur Saisonnier', description: "Alignez votre alimentation sur les rythmes de la nature et la sagesse de l'Ayurveda.", presentMoment: 'Moment Présent', weeklyRituals: 'Rituels Culinaires Hebdo', wisdomTitle: 'Honorer votre Agni', wisdomDesc: 'Votre feu digestif est au plus fort quand le soleil est au zénith. Mangez entre 12h00 et 13h30.', ritualButton: 'Rappels de Rituels' },
    connect: { sampark: 'Sampark • Contact', title: 'Contactez-nous', description: "Que vous cherchiez une recette, partagiez vos avis ou exploriez des partenariats, nos portes sont ouvertes.", direct: 'Canaux Directs', emailUs: 'Email', studio: 'Studio', location: 'Pune, Maharashtra, Bharat', quote: "Cuisiner est une conversation entre l'âme et le sol.", fullName: 'Nom Complet', email: 'E-mail', phone: 'Téléphone', reason: 'Raison du Contact', message: 'Votre Message', send: 'Envoyer', selectReason: 'Choisir une raison', successTitle: 'Merci!', successDesc: 'Merci de nous avoir contactés. Umesh vous répondra bientôt.' },
    footer: { quote: 'Élever le mode de vie végétarien avec passion et tradition.', visits: 'Visites Totales', curated: 'Créé & Édité par', rights: 'TOUS DROITS RÉSERVÉS' }
  }
};
